name: free_palestine
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.1.0+10

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.3.3
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  change_app_package_name: ^1.1.0
  shared_preferences: ^2.2.2
  internet_connection_checker: ^1.0.0+1
  flutter_native_splash: ^2.3.4
  flutter_launcher_icons: ^0.13.1
  bloc: ^8.1.2
  #sqflite: ^2.2.8
  #url_launcher: ^6.1.11
  awesome_dialog: ^3.1.0
  #flutter_keyboard_visibility: ^5.4.1
  smooth_page_indicator: ^1.1.0
  #percent_indicator: ^4.2.3
  #google_mobile_ads: ^3.1.0
  flutter_spinkit: ^5.2.0
  lottie: ^2.7.0
  percent_indicator: ^4.2.3
  carousel_slider: ^4.2.1
  word_search_safety: ^0.1.2-nullsafety.1
  url_launcher: ^6.2.1
  intl: ^0.18.1

# flutter_native_splash
flutter_native_splash:
  color: "#dcf8ff"
  image: assets/images/splash.png
  fill: true
  fullscreen: true
  android: true
  ios: true
  web: true
#  android_12:
#    image: assets/images/splash12.png
#    color: "#ffffff"
#    branding: assets/images/splash122.png
  #color_dark: "#042a49"
  #background_image_dark: "assets/dark-background.png"
  #image_dark: assets/splash-invert.png
  #branding_dark: assets/dart_dark.png

#flutter_icons
flutter_icons:
  android: true
  image_path: "assets/images/icon.png"
  ios: true


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/json/
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo/Cairo-Light.ttf
        - asset: assets/fonts/Cairo/Cairo-SemiBold.ttf
        - asset: assets/fonts/Cairo/Cairo-Black.ttf
        - asset: assets/fonts/Cairo/Cairo-ExtraLight.ttf
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf